# Generated by Django 4.1.2 on 2022-10-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'word_table',
            },
        ),
    ]
